// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from handy.djinni

#pragma once

#include <cstdint>
#include <string>
#include <vector>

namespace generated {

class ImgTransformWrapper {
public:
    virtual ~ImgTransformWrapper() {}

    static std::vector<uint8_t> cvtGray(const std::vector<uint8_t> & image, int32_t frame_height, int32_t frame_width, int32_t rotation_degrees);

    static std::string hello(const std::string & name);
};

}  // namespace generated
