// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from handy.djinni

#pragma once

#include "ImgTransformWrapper.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeImgTransformWrapper final : ::djinni::JniInterface<::generated::ImgTransformWrapper, NativeImgTransformWrapper> {
public:
    using CppType = std::shared_ptr<::generated::ImgTransformWrapper>;
    using CppOptType = std::shared_ptr<::generated::ImgTransformWrapper>;
    using JniType = jobject;

    using Boxed = NativeImgTransformWrapper;

    ~NativeImgTransformWrapper();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeImgTransformWrapper>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeImgTransformWrapper>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeImgTransformWrapper();
    friend ::djinni::JniClass<NativeImgTransformWrapper>;
    friend ::djinni::JniInterface<::generated::ImgTransformWrapper, NativeImgTransformWrapper>;

};

}  // namespace djinni_generated
