// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from handy.djinni

#pragma once

#include "CoreLibInterface.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeCoreLibInterface final : ::djinni::JniInterface<::generated::CoreLibInterface, NativeCoreLibInterface> {
public:
    using CppType = std::shared_ptr<::generated::CoreLibInterface>;
    using CppOptType = std::shared_ptr<::generated::CoreLibInterface>;
    using JniType = jobject;

    using Boxed = NativeCoreLibInterface;

    ~NativeCoreLibInterface();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeCoreLibInterface>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeCoreLibInterface>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeCoreLibInterface();
    friend ::djinni::JniClass<NativeCoreLibInterface>;
    friend ::djinni::JniInterface<::generated::CoreLibInterface, NativeCoreLibInterface>;

};

}  // namespace djinni_generated
